### ISSUE TITLE
Can't initializeAnalysisComponent

### ISSUE THREAD

**Issue by ptcongbk** [webis-de/ACL-18#1]
Thank you very much for you code sharing. Your idea is so great that I would like to try testing. But when I ran this command 'java -cp acl18-bundle.jar de.aitools.ie.articles.FeatureExtractor VERACITY data/xmi data/veracity' , it raised a bug like this.

Caused by: org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "de.aitools.ie.uima.analysis.segmentation.TexHyphJSyllableDetector" failed.  (Descriptor: jar:file:/D:/Projects/BuzzFeed/master/acl18-bundle.jar!/uima-descriptors/primitive-AEs/segmentation/TextHyphJSyllableDetector.xml)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:264)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:169)
        at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
        at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
        at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
        at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:407)
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:256)
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:429)
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:373)
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:186)
        at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
        at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
        at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
        at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:371)
        ... 5 more
Caused by: java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:130)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at de.aitools.ie.uima.analysis.segmentation.TexHyphJSyllableDetector.initialize(TexHyphJSyllableDetector.java:87)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:262)
      
It is great if you can check/fix?

**Comment by johanneskiesel** [comment]
Thanks for the hint! I'm currently traveling, but will check and fix at the start of next week

**Comment by johanneskiesel** [comment]
So I started from a cleanly checked out repository, and it seems I missed to include two projects.

Please check the updated "Resources" section of the README: https://github.com/webis-de/ACL-18/blob/master/README.md#resources . Unfortunately, setting up the Tree Tagger is always an adventure. I also don't have a Windows system close, but I hope this helps you.

Please tell me whether that works or provide me with another error message ;)

**Comment by ptcongbk** [comment]
It worked like a charm. Thank you very much
P/S: the link for english.par seems to be wrong.
